### ISSUE TITLE
Some model aren't found

### ISSUE THREAD

**Issue by Nausx** [koseven/koseven#183]
As I said I'm having trouble with some model and when I try `ORM::factory('ModelName')` I get an error saying the `Model_ModenName not found`. Though it works find with other models but i'm not completly sure it's a bug, maybe I did something wrong and i'll put all information you ask here.

Here is the model and the orm configuration, 

```php
class Model_Institution extends ORM{
    protected $_table_name = 'institutions';

    protected $_has_many   = [
        'faculties'    => ['model' => 'Faculty',    'foreign_key' => 'institution_id'],
        'departements' => ['model' => 'Department', 'foreign_key' => 'institution_id'],
    ];
}
```

```php
Kohana::modules(array(
	// 'encrypt'    => MODPATH.'encrypt',    // Encryption supprt
	//'auth'       => MODPATH.'auth',       // Basic authentication
	// 'cache'      => MODPATH.'cache',      // Caching with multiple backends
	// 'codebench'  => MODPATH.'codebench',  // Benchmarking tool
	 'database'   => MODPATH.'database',   // Database access
	// 'image'      => MODPATH.'image',      // Image manipulation
	// 'minion'     => MODPATH.'minion',     // CLI Tasks
	 'orm'        => MODPATH.'orm',        // Object Relationship Mapping
	// 'pagination' => MODPATH.'pagination', // Pagination
	// 'unittest'   => MODPATH.'unittest',   // Unit testing
	// 'userguide'  => MODPATH.'userguide',  // User guide and API documentation
	));
```

The error message from the log
```
2017-12-09 15:39:23 --- EMERGENCY: Error [ 0 ]: Class 'Model_Institution' not found ~ MODPATH/orm/classes/Kohana/ORM.php [ 46 ] in /home/nausx/workspace/porto/application/classes/Controller/BaseController.php:89
2017-12-09 15:39:23 --- DEBUG: #0 /home/nausx/workspace/porto/application/classes/Controller/BaseController.php(89): Kohana_ORM::factory('Model_Instituti...')
#1 /home/nausx/workspace/porto/application/classes/Controller/BaseController.php(132): Controller_BaseController->addManager('Martin', 'Lachance', 'email1@email.ca')
#2 /home/nausx/workspace/porto/application/classes/Controller/BaseController.php(16): Controller_BaseController->fixtures()
#3 /home/nausx/workspace/porto/system/classes/Kohana/Controller.php(69): Controller_BaseController->before()
#4 [internal function]: Kohana_Controller->execute()
#5 /home/nausx/workspace/porto/system/classes/Kohana/Request/Client/Internal.php(97): ReflectionMethod->invoke(Object(Controller_Profile))
#6 /home/nausx/workspace/porto/system/classes/Kohana/Request/Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 /home/nausx/workspace/porto/system/classes/Kohana/Request.php(993): Kohana_Request_Client->execute(Object(Request))
#8 /home/nausx/workspace/porto/public/index.php(118): Kohana_Request->execute()
#9 {main} in /home/nausx/workspace/porto/application/classes/Controller/BaseController.php:89
```

Thx for your help.

**Comment by svenbw** [comment]
Check your filename, including the upper- and lowercase.

**Comment by Nausx** [comment]
Filename of the model is `institution.php` not plural and all lowercase as shown in documentation.

**Comment by svenbw** [comment]
Since your model name contains an capital 'I' your filename should also contain a uppercase 'I'.
So `Model_Institution` -> `Institution.php', ...

**Comment by jstrobel** [comment]
Or if you have a lot classes add this to your bootstrap.php

spl_autoload_register(array('Kohana', 'auto_load_lowercase'));

**Comment by Nausx** [comment]
Ok fine, it works, thank you
